version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - /usr/local/docker/elasticsearch/volume/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /usr/local/docker/elasticsearch/volume/data:/usr/share/elasticsearch/data
      - /usr/local/docker/elasticsearch/volume/plugins:/usr/share/elasticsearch/plugins
    networks:
      - es_network
  kibana:
    image: kibana:7.17.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - /usr/local/docker/elasticsearch/volume/kibanaconfig:/usr/share/kibana/config
      - /usr/local/docker/elasticsearch/volume/kibanadata:/usr/share/kibana/data
    networks:
      - es_network
networks:
  es_network:
    driver: bridge
